### ISSUE TITLE
issue black window and no rendered output via Vulkan with a AMD Radeon RX 6600

### ISSUE THREAD

**Issue by Trunkvv** [Naitsirc98/Vulkan-Tutorial-Java#15] opened 2022-12-12 19:17 UTC
Hi again,

I have encountered the most curious issue, which I can pinpoint, but don't know whom to address it to.

It all starts with your port, so I'll start with you.

I've been developping on your port, introducing support for multiple models. 
I've switched from my old desktop to a newer one.
But on the new desktop, the code runs without any error, but the vulkan window is entirely black.
So Ive tried a few things to pinpoint any cause.
1. All your code, starting from Ch15HelloTriangle.java, are giving all black windows. So the cause is unlikely in my adjustments. 
2. I've double checked all driver versions of GPU, vulkanSDK, VSC, JavaSDK, not a single difference found.
3. Reinstalling windows entirely, didn't fix it.
4. installing RenderDoc, but no overlay presented after launching the application JAR, so that's odd as well.
5. installed VS community C++ setup, building and running the original C++ code of those chapters, did give me a running application with the expected visuals as the triangle, squares, viking room and chalet. So it's somewhere in the java port or libraries
6.  But most stunning was, that swapping my AMD RX 6600 for my older RX 570, fixed the issue, even without reinstalling the same driver!!!

So my question is to you, how can we pinpoint the issue that the code doesn't display visuals on my RX 6600?

Hopefully you have a good suggestion.

Cheers.

(I'll come back to you with all version number if that helps)

**Comment by Naitsirc98** [comment] 2022-12-14 12:52
Hi,

I cannot reproduce the error because I work with a RTX 3080.

It seems that is something related to LWJGL. Are you using the latest version or the one I used in this port?

You said that the original C++ tutorial works just fine, but are you running the latest code of the C++ tutorial? Please keep in mind that the original tutorial, as you already told me, has been updated, so maybe the changes in the new version are what fixes the problem. Try running an older version of the C++ tutorial (from 2 years ago or so).

**Comment by Trunkvv** [comment] 2022-12-14 15:24
Hi,

Thank you for responding. 

I'm using the latest LWJGL 3.3.1.  (latest VulkanSDK 1.3.231.1 and latest JDK-17.0.5.8)

I am suspecting something in LWJGL (or GLFW) as well, so I've checked the following code below, which rendered fine. That's not helping relating it to LWJGL. I'll test some other Vulkan demos on https://github.com/LWJGL/lwjgl3-demos as well.
https://raw.githubusercontent.com/LWJGL/lwjgl3/master/modules/samples/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java

I'll keep you posted on my findings

**Comment by Trunkvv** [comment] 2022-12-15 09:03
Well, all Vulkan demos on https://github.com/LWJGL/lwjgl3-demos are rendering fine on my RX6600. I'll investigate the difference between your port 
https://raw.githubusercontent.com/Naitsirc98/Vulkan-Tutorial-Java/master/src/main/java/javavulkantutorial/Ch15HelloTriangle.java

and the look alike demo on 
https://github.com/LWJGL/lwjgl3-demos/blob/main/src/org/lwjgl/demo/vulkan/ColoredTriangleDemo.java

**Comment by Trunkvv** [comment] 2023-01-11 10:46
Well, found a workaround! I was looking at the difference of the working code:
https://github.com/LWJGL/lwjgl3-demos/blob/main/src/org/lwjgl/demo/vulkan/ColoredTriangleDemo.java
and not working on specifically my RX6600:
https://github.com/Naitsirc98/Vulkan-Tutorial-Java/blob/master/src/main/java/javavulkantutorial/Ch15HelloTriangle.java

ColoredTriangleDemo (lwjgl3-demos) is using the same queue family for graphics and presenting.
Ch15HelloTriangle (Vulkan-Tutorial-Java) allowed different families, and ended up select for present a different one with my RX6600. When I forced it to select the same as the graphics queue family (and same as on the working demo), the issue with a presented black screen vanished!

So I don't know why it's presenting a black screen, but I made it disappear....

**Comment by Trunkvv** [comment] 2023-01-11 10:50
That's happening in findQueueFamilies(). To solve my issue with the presented black screen, I've altered the code so both values for presentFamily and graphicsFamily are set to 0.

**Comment by Naitsirc98** [comment] 2023-01-13 09:51
Hi, 

I'm glad you finally found a solution. It must be something with that GPU in particular since it worked with your previous graphics card and with my RTX 3080 it selects 2 different queue families for graphics and presentation too but it works just fine.

Maybe you can find more info about this problem in AMD or Vulkan forums.

I'm closing this issue since it's already working for you.

**Closed by Naitsirc98** 2023-01-13 09:51 UTC
